# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{list-for}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Hunter"]
  s.date = %q{2011-05-24}
  s.description = %q{list-for is a list builder for an array of objects, easily allowing overriding of how any aspect of the list is generated}
  s.email = %q{hunterae@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/views/list_for/_list_for.html.erb",
    "lib/list-for.rb",
    "lib/list_for/engine.rb",
    "lib/list_for/helper_methods.rb",
    "lib/list_for/list_for.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/hunterae/list-for}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{list-for is a list builder for an array of objects, easily allowing overriding of how any aspect of the list is generated}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<list-for>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<building-blocks>, [">= 0"])
    else
      s.add_dependency(%q<list-for>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.0.0"])
      s.add_dependency(%q<building-blocks>, [">= 0"])
    end
  else
    s.add_dependency(%q<list-for>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.0.0"])
    s.add_dependency(%q<building-blocks>, [">= 0"])
  end
end

